#!/bin/bash

if [ -z $1 ] || [ -z $2 ]
then
	echo "Not enough arguments passed!"
	exit
fi

diff <(sha256sum $1) $2 

if [ $? -eq 0 ]
then
	echo "The file is OKAY!"
else
	echo "The file FAILED verification!!!"
fi
