#!/bin/bash

BAT_LEVEL=$(cat /sys/class/power_supply/BAT1/capacity)
CONSERVATION_MODE=$(cat /sys/bus/platform/drivers/ideapad_acpi/VPC*/conservation_mode)

if [[ $BAT_LEVEL -ge 80 && $CONSERVATION_MODE == 0 ]]
then
	echo 1 | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode
	echo "Battery is at 80%. Conservation mode enabled."
elif [[ $BAT_LEVEL -lt 80 && $CONSERVATION_MODE == 1 ]]
then
	echo 0 | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode
	echo "Battery is below 80%. Conservation mode disabled."
fi

exit 0
