#!/bin/bash

sudo /usr/local/bin/bios_power_mode INTELLIGENT_COOLING

sudo tuned-adm profile balanced

# Set cpu governor to powersave
sudo cpupower frequency-set --governor schedutil
# sudo cpupower frequency-set --min 1400000
# sudo cpupower frequency-set --max 1700000

# disable usb autosuspend
echo 'on' > '/sys/bus/usb/devices/usb2/power/control';
echo 'on' > '/sys/bus/usb/devices/usb1/power/control';
echo 'on' > '/sys/bus/usb/devices/1-3/power/control';

# disable nvidia card power save
echo 'on' > '/sys/bus/pci/devices/0000:01:00.0/power/control';

echo '0' > '/proc/sys/vm/dirty_writeback_centisecs';

# stops autosuspend on steelseries mouse
# echo 'on' > '/sys/bus/usb/devices/1-3/power/control';

# turn off several powersaving configs
# /usr/sbin/hciconfig hci0 up &> /dev/null &
# echo 'on' > '/sys/block/sda/device/power/control';
# echo 'on' > '/sys/bus/pci/devices/0000:00:17.0/ata1/power/control';
# echo 'on' > '/sys/bus/pci/devices/0000:00:17.0/ata2/power/control';
# echo 'on' > '/sys/bus/pci/devices/0000:00:17.0/ata3/power/control';
# echo 'on' > '/sys/bus/pci/devices/0000:00:16.0/power/control';
# echo 'on' > '/sys/bus/pci/devices/0000:00:1c.0/power/control';
# echo 'on' > '/sys/bus/pci/devices/0000:00:1c.5/power/control';
