#!/bin/bash

/usr/local/bin/bios_power_mode INTELLIGENT_COOLING

tuned-adm profile balanced

# Set cpu governor to powersave
cpupower frequency-set --governor schedutil

# Turn off for steelseries mouse
echo 'on' > '/sys/bus/usb/devices/1-2/power/control';

# disable usb autosuspend
echo 'on' > '/sys/bus/usb/devices/usb2/power/control';
echo 'on' > '/sys/bus/usb/devices/usb1/power/control';
echo 'on' > '/sys/bus/usb/devices/1-3/power/control';

# disable nvidia card power save
echo 'on' > '/sys/bus/pci/devices/0000:01:00.0/power/control';

echo '0' > '/proc/sys/vm/dirty_writeback_centisecs';

# stops autosuspend on steelseries mouse
echo 'on' > '/sys/bus/usb/devices/1-3/power/control';
