#!/bin/bash

# Check if pc is in battery mode
BAT_STATUS=$(tlp-stat | grep "Mode " | awk -F ' ' '{ print $3 }')

if [ $BAT_STATUS != "battery" ]
then
	>&2 echo "Laptop is not in battery mode"
	exit 1
fi

# Turn off for steelseries mouse
echo 'on' > '/sys/bus/usb/devices/1-2/power/control';

# Set BIOS mode to power saving
/usr/local/bin/bios_power_mode BATTERY_SAVING

tuned-adm profile powersave

# Set cpu governor to powersave
cpupower frequency-set --governor powersave

echo 'powersupersave' | tee /sys/module/pcie_aspm/parameters/policy

# Disable bluetooth powersave
/usr/sbin/hciconfig hci0 up &> /dev/null &
# Disable USB device autosuspend
echo 'on' > '/sys/bus/usb/devices/usb2/power/control';

# amdgpu dpm settings
#echo 'battery' | tee /sys/class/drm/card0/device/power_dpm_state
echo 'low' > /sys/class/drm/card0/device/power_dpm_force_performance_level

#powertop stuff

echo 'on' > '/sys/bus/usb/devices/1-3/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:01:00.0/power/control';
echo '1500' > '/proc/sys/vm/dirty_writeback_centisecs';
echo 'auto' > '/sys/bus/usb/devices/1-3/power/control';
echo '1' > '/sys/module/snd_hda_intel/parameters/power_save';
echo 0 | tee /sys/devices/system/cpu/cpufreq/boost
tlp usb
echo 'on' > '/sys/bus/pci/devices/0000:01:00.0/power/control';
