#!/bin/bash

# Check if pc is in battery mode
BAT_STATUS=$(cat /sys/class/power_supply/BAT1/status)

if [ $BAT_STATUS != "Discharging" ]
then
	>&2 echo "Laptop is not in battery mode"
	exit 1
fi

# Set BIOS mode to power saving
/usr/local/bin/bios_power_mode BATTERY_SAVING

tuned-adm profile powersave

# Turn off powersave for bluetooth mouse and usb devices
echo 'on' > '/sys/bus/usb/devices/3-4/power/control';
echo 'on' > '/sys/bus/usb/devices/1-2/power/control'
echo 'on' > '/sys/bus/usb/devices/usb4/power/control';
echo 'on' > '/sys/bus/usb/devices/usb3/power/control';
echo 'on' > '/sys/bus/usb/devices/usb2/power/control';
echo 'on' > '/sys/bus/usb/devices/usb1/power/control';
echo 'on' > '/sys/bus/usb/devices/3-2/power/control';

echo 'on' > '/sys/bus/usb/devices/3-4/power/control';
echo 'disabled' > '/sys/bus/usb/devices/3-2/power/wakeup';

echo 'on' > '/sys/bus/pci/devices/0000:01:00.0/power/control';

# Set cpu governor to powersave
cpupower frequency-set --governor powersave

echo 'powersupersave' | tee /sys/module/pcie_aspm/parameters/policy

# Disable bluetooth powersave
/usr/sbin/hciconfig hci0 up &> /dev/null &

# amdgpu dpm settings
#echo 'battery' | tee /sys/class/drm/card0/device/power_dpm_state
echo 'low' > /sys/class/drm/card0/device/power_dpm_force_performance_level

# Misc
echo 'auto' > '/sys/bus/pci/devices/0000:01:00.0/power/control';
echo '1500' > '/proc/sys/vm/dirty_writeback_centisecs';
echo '1' > '/sys/module/snd_hda_intel/parameters/power_save';
echo 0 | tee /sys/devices/system/cpu/cpufreq/boost
tlp usb
echo 'on' > '/sys/bus/pci/devices/0000:01:00.0/power/control';
