#!/bin/bash
echo 'on' > '/sys/bus/usb/devices/usb2/power/control';
echo 'on' > '/sys/bus/usb/devices/1-8/power/control';
echo 'on' > '/sys/bus/usb/devices/usb1/power/control';
echo 'on' > '/sys/bus/usb/devices/1-3/power/control';
