#!/bin/bash

#/home/avalente/scripts/kill_akonadi
akonadictl stop
# sudo systemctl start thermald
sudo tuned-adm profile powersave
#sudo service tlp start

# Set cpu governor to powersave
# sudo cpupower frequency-set --governor powersave
sudo cpupower frequency-set --governor schedutil
# sudo cpupower frequency-set --min 1400000
sudo cpupower frequency-set --max 1700000

echo 'powersupersave' | sudo tee /sys/module/pcie_aspm/parameters/policy

# sudo /home/avalente/Documents/Scripts/disable_services

# sudo powertop --auto-tune

# echo 'med_power_with_dipm' > '/sys/class/scsi_host/host0/link_power_management_policy';
# echo 'med_power_with_dipm' > '/sys/class/scsi_host/host1/link_power_management_policy';
# echo 'med_power_with_dipm' > '/sys/class/scsi_host/host2/link_power_management_policy';
# Audio autosuspend
# echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.3/power/control';

#powertop stuff
echo 'med_power_with_dipm' > '/sys/class/scsi_host/host0/link_power_management_policy';

# Disable auto suspend to HP usb mouse
echo 'on' > '/sys/bus/usb/devices/3-2/power/control';
# echo 'auto' > '/sys/bus/usb/devices/1-3/power/control';
echo 'on' > '/sys/bus/usb/devices/1-3/power/control';

# nvidia card?
echo 'auto' > '/sys/bus/pci/devices/0000:01:00.0/power/control';

# enable usb autosuspend
# echo 'auto' > '/sys/bus/usb/devices/usb2/power/control';
# echo 'auto' > '/sys/bus/usb/devices/1-8/power/control';
# echo 'auto' > '/sys/bus/usb/devices/usb1/power/control';

# further power savings
# echo 'auto' > '/sys/bus/pci/devices/0000:00:17.0/ata3/power/control';
# echo 'auto' > '/sys/bus/pci/devices/0000:00:17.0/ata2/power/control';
# echo 'auto' > '/sys/bus/pci/devices/0000:00:17.0/ata1/power/control';
# echo 'auto' > '/sys/block/sda/device/power/control';

# zenbook specific
# echo 'auto' > '/sys/bus/usb/devices/1-3/power/control';
echo '1500' > '/proc/sys/vm/dirty_writeback_centisecs';
echo 'auto' > '/sys/bus/usb/devices/1-3/power/control';
echo 'med_power_with_dipm' > '/sys/class/scsi_host/host1/link_power_management_policy';
echo '1' > '/sys/module/snd_hda_intel/parameters/power_save';
echo 0 | sudo tee /sys/devices/system/cpu/cpufreq/boost
sudo tlp usb
echo 'on' > '/sys/bus/pci/devices/0000:01:00.0/power/control';

# /usr/sbin/hciconfig hci0 up &> /dev/null &
# echo 'on' > '/sys/bus/pci/devices/0000:04:00.6/power/control';
